services:
  db:
    image: postgres:15
    container_name: smart-insulin-db
    environment:
      POSTGRES_DB: smart-insulin-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1111
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d smart-insulin-db"]
      interval: 5s
      timeout: 5s
      retries: 5

  hba1c-builder:
    build: ./hba1c-lib
    volumes:
      - ./hba1c-lib/dist:/dist

  backend:
    build: ./smart-insulin-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/smart-insulin-db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1111
    volumes:
      - ./hba1c-lib/dist:/usr/local/lib/nativelibs
    depends_on:
      db:
        condition: service_healthy
      hba1c-builder:
        condition: service_completed_successfully

  frontend:
    build:
      context: ./smart-insulin-app
      args:
        VITE_API_BASE_URL: ""
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  postgres_data: